### ISSUE TITLE
symbol breaks on pass-through colocation

### ISSUE THREAD

**Issue by mattkrick** [relay-tools/relay-compiler-language-typescript#59]
First & foremost, **THANK YOU**. The amount of work that you've put into making this a reality is no short of monumental & it's amazing! My app is a hot mess of JS, Flow, and TS and this plugin handles it all with ease.

I've been using it for about a week and there's just one thing I can't seem to do:

I've got a fragment like this:
```
fragment Foo_item on Item {
  ...Bar_item
  id
}
```

I tried writing something like this: `<Bar item={item}/>`

i got this:

```
TS2322: Type 'Foo_item' is not assignable to type 'Bar_item'.
  Types of property '" $refType"' are incompatible.
  Type 'typeof _Foo_item$ref' is not assignable to type 'typeof _Bar_item$ref'.
```

I tried running the example (used `npm pack` and updated the example version to 1.0.1) to make sure i wasn't crazy & i got this:

```
Error:(56, 21) TS2322: Type '{ viewer: TodoApp_viewer; }' is not assignable to type 'IntrinsicAttributes & Pick<Props & { relay: never; }, "viewer"> & ComponentRef & { children?: Rea...'.
  Type '{ viewer: TodoApp_viewer; }' is not assignable to type 'Pick<Props & { relay: never; }, "viewer">'.
    Types of property 'viewer' are incompatible.
      Type 'TodoApp_viewer' is not assignable to type 'TodoList_viewer'.
        Property 'todos' is missing in type 'TodoApp_viewer'.
```

Seems related to #58, although just like the example I've got all my artifacts in a single folder.
FWIW I wouldn't mind if the symbol was removed from the types. I use relay with storybook & if the symbol were removed then I wouldn't have to cast my mock input data to the appropriate type.

**Comment by alloy** [comment]
Hey, thanks for the kind words!

Would it be possible for you to provide a failing example app or a failing test in this repo?

**Comment by mattkrick** [comment]
I _think_ the example app in this repo should suffice. Both errors have the same root cause, which requires casting the object you're passing down to the type that the child expects.

**Comment by alloy** [comment]
Is the sole issue here around manually passing data into a component that would normally be fetched by Relay?

**Comment by mattkrick** [comment]
nope, just check out the example todo app in this repo & you'll see the typescript errors

**Comment by alloy** [comment]
Ohhh, thanks for making me look twice at the example app. I was not seeing the type errors show up because of a local issue. I have fixed them, it was largely that I hadn’t upgraded `@types/react-relay` and `@types/relay-runtime`. Could it be that this is the cause for you?

Just yesterday did I surface those peer dependencies https://github.com/relay-tools/relay-compiler-language-typescript/commit/77ba776e0d8c61dedd44d5ae12e936e51ef2c9d9 as well, so that should hopefully make this cause more clear in the future.

**Comment by alloy** [comment]
@mattkrick Can you see if outdated DT typings might have been the problem in your case?

Regarding having to cast manually created data due to the unique symbol, while I agree it’s a bit of a nuisance, I think that type checking the fragment references and not having to cast them in your component code is preferable over having to cast in tests/stories.

**Comment by mattkrick** [comment]
Hey @alloy looks good!
The only thing it didn't fix in my app was handling for passthrough components.

Let's say I have a presentational component sandwiched in between 2 fragment containers. The presentational component passes down the `viewer` prop like it's a black box.

For example `App` has a presentational child called `Foo`, which has a container child `Bar`.
Here's a repro:
https://github.com/relay-tools/relay-compiler-language-typescript/compare/master...mattkrick:passthrough-component-test

The error I get is:
```
Error:(12, 25) TS2322: Type '{ children?: ReactNode; viewer: TodoListBar_viewer; }' is not assignable to type 'IntrinsicAttributes & MappedFragmentProps<Pick<Props, "viewer">> & ComponentRef & { children?: Re...'.
  Type '{ children?: ReactNode; viewer: TodoListBar_viewer; }' is not assignable to type 'MappedFragmentProps<Pick<Props, "viewer">>'.
    Types of property 'viewer' are incompatible.
      Type 'TodoListBar_viewer' is not assignable to type '_FragmentRefs<symbol>'.
        Property '" $fragmentRefs"' is missing in type 'TodoListBar_viewer'.
```

It's easy enough to just make the passhtrough component prop have an `any` type, but the fragment symbol is the only thing stopping it from being a little more expressive.

**Comment by kastermester** [comment]
@mattkrick You need to type up TodoListFoo differently. The viewer prop here needs to be typed to `TodoApp_viewer`. When you don't have Relay containers in between the mix the prop types don't change when you pass the data through components (remember, it really is just data objects). What makes this work in practice is the higher order component you create when calling `create{Fragment,Refetch,Pagination}Container` is remapping the data for you.

Does this make sense?

**Comment by mattkrick** [comment]
Ah that's good! So the presentational component is more closely related to the parent type instead of the child type. I like it.

one caveat, let's say the parent doesn't have that fragment:

```graphql
fragment App_viewer on User {
  viewer {
    todo {
      ...Bar_todo
    }
  }
}
```

```jsx
// in App.ts
<Foo todo={viewer.todo}/>
```

in this case, the prop type should be `App_viewer["todo"]`? (if there's a cleaner way to grab subtypes, lemme know!)

**Comment by kastermester** [comment]
@mattkrick That is correct. Regarding the "cleaner" way of grabbing subtypes, we actually have a different discussion on this in #64.

Personally I think a cleaner way would be great, but I think we need to track that in the official relay repository (I think @alloy might already have created an issue to discuss it) - such that we can have the same features between the Flow and TypeScript implementations. As of right now we have tried to mirror the Flow features 1:1 and haven't attempted at making Relay with TypeScript any different than Relay with Flow. This is something I feel we should continue to maintain - in this way we don't need any special documentation other than setup and guidelines - which is obviously an area we still need to improve on.

**Comment by mattkrick** [comment]
ah, works for me.
one last hurdle while trying this out-- what if the type in the parent is a list? that list gets converted into a ReadonlyArray with an unnamed generic, so there's nothing to grab.

fragment App_viewer on User {
  viewer {
    todos {
      ...Bar_todo
    }
  }
}

```jsx
// in App.ts#render
return viewer.todos.map((todo) => <Foo todo={todo}/>)
```

in this case, what type should I use for `todo` in the `Foo` passthrough component?

**Comment by alloy** [comment]
Does `App_viewer[“viewer”][“todos”][0]` work for your case?

**Comment by mattkrick** [comment]
:open_mouth: ...i had no idea i could do that!

yep, that shuts me up. thanks for all your support!

**Comment by alloy** [comment]
Hah, yeah it isn’t intuitive. Until you realise that indexed subscripting also allows for referencing specific elements in a tuple type.

Glad to hear you’re all set now, though!
